language: go
go_import_path: github.com/newrelic/go-agent
go:
    - 1.3
    - 1.4    
    - 1.5    
    - 1.6    
    - 1.7
    - 1.8    
    - tip
matrix:
  allow_failures:
    - go: tip
    
        
    