language: go
go_import_path: github.com/newrelic/go-agent
go:
    - 1.3
    - 1.4    
    - 1.5    
    - 1.6    
    - 1.7
    - 1.8    
    - 1.9
    - tip

# Skip the install step. Don't `go get` dependencies. Only build with the
# code in vendor/
install: true

matrix:
  allow_failures:
    - go: tip

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

script:
  - test -z "$(gofmt -s -l $GO_FILES)"
  - go test -v -race ./...
  - go vet ./...
